{% set name = "anaconda-cloud-auth" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  noarch: generic
  number: 0

requirements:
  run:
    - anaconda-auth ={{ version }}

test:
  imports:
    - anaconda_cloud_auth
    - anaconda_auth
  commands:
    - python -c "from anaconda_cloud_auth import __version__; assert __version__ == \"{{ version }}\""
    - python -c "from anaconda_auth import __version__; assert __version__ == \"{{ version }}\""

about:
  summary: A client auth library for Anaconda.cloud APIs
  home: https://anaconda.cloud
  license: BSD-3-Clause
  license_file: {{ RECIPE_DIR }}/LICENSE

extra:
  recipe-maintainers:
    - albertdefusco
    - mattkram
