{% set name = "anaconda-cloud-auth" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anaconda_cloud_auth-{{ version }}.tar.gz
  sha256: f2e92a94e612d4d2fd11c02f41dffb29f53ba9e5e7443884edc6c6c440096ab4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - hatchling
    - hatch-vcs >=0.3
    - setuptools-scm >=7.1
    - pip
  run:
    - python >=3.8,<3.12
    - keyring
    - pkce
    - python-dotenv
    - pydantic <2.0
    - pyjwt
    - requests
    - cryptography >=3.4.0
    - semver <3

test:
  imports:
    - anaconda_cloud_auth
  commands:
    - python -c "from anaconda_cloud_auth import __version__; assert __version__ == \"{{ version }}\""

about:
  summary: A client auth library for Anaconda.cloud APIs
  home: https://anaconda.cloud
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - albertdefusco
    - mattkram
